name: avencia
description: A crypto banking app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.4.0"
dependencies:
  flutter:
    sdk: flutter
  helpers:
    path: ./helpers
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.0
  dartz: ^0.10.1
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutterfire_ui: ^0.4.2+3
  firebase_core: ^2.1.1
  http: ^0.13.4
  qr_flutter: ^4.0.0
  step_progress_indicator: ^1.0.2
  image_picker: ^0.8.6
  google_fonts: ^3.0.1
  go_router: ^5.1.5
  rx_shared_preferences: ^3.0.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  english_words: ^4.0.0
  fake_async: ^1.3.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/logo_square_big.png"
flutter:
  uses-material-design: true
  assets:
    - assets/logo_with_light_title.png
    - assets/logo_with_dark_title.png
    - assets/logo_square_big.png
    - assets/avatar.png
    # The icons are from https://github.com/spothq/cryptocurrency-icons
    - assets/currencies/
