name: avencia
description: A crypto banking app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.2
  dartz: ^0.10.1
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutterfire_ui: ^0.4.2+3
  firebase_core: ^1.19.2
  http: ^0.13.4
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  english_words: ^4.0.0
  fake_async: ^1.3.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo_white.png
